// import { RaisedInvoice } from "@/components/Table/RaisedInvoiceTable"
// export const data: RaisedInvoice[] = [
   
//     {
//       sNo: 56783,
//       invoiceNo: 59234,
//       status: "Final Notice Sent",
//       buyersName: "Kristin Watson",
//       buyersContact: "Esther Howards",
//       invoiceGeneratedName: "Developers Name",
//       invoiceGeneratedDate: "12/04//2024",
//       invoiceDate: "13/04//2024",
//       invoiceAmount: 12000,
//       GST: 12435,
//       tds: 12000,
//       amountAfterTdsDeducted: 12000,
//       finalInvoice: 12000,
//       invoiceHandedOverTo: "Shagun Khanna",
//       cancellationDate: "12/04//2024",
//       transaction: "Esther Howard",
//       representative: "jenny",
//       projectsName: "99 acres",
//       unitNo: "A-3456",
//       settinRepresentative: "Shagun Khanna",
//       leadSource: "99 acres",
//       basePrice: 12000,
//       totalPrice: 200000,
//       bookingDate: "12/12/2023",
//       tentativeDateAgreement: "12/03/2024",
//       tentativeDateRecieve: "12/03/2025",
//       totalComissions: 2,
//       cpComissions: 2,
//       discountOffered: 3,
//       revenue: 10476484, 
//       comment: "awesome"
//     },
//     {
//       sNo: 12345,
//       invoiceNo: 67890,
//       status: "Pending",
//       buyersName: "John Doe",
//       buyersContact: "Jane Smith",
//       invoiceGeneratedName: "Builders Inc",
//       invoiceGeneratedDate: "15/04//2024",
//       invoiceDate: "16/04//2024",
//       invoiceAmount: 15000,
//       GST: 13579,
//       tds: 15000,
//       amountAfterTdsDeducted: 15000,
//       finalInvoice: 15000,
//       invoiceHandedOverTo: "Shagun Khanna",
//       cancellationDate: "15/04//2024",
//       transaction: "Jane Smith",
//       representative: "Alex",
//       projectsName: "Green Gardens",
//       unitNo: "B-9876",
//       settinRepresentative: "Shagun Khanna",
//       leadSource: "Green Gardens",
//       basePrice: 15000,
//       totalPrice: 250000,
//       bookingDate: "15/12/2023",
//       tentativeDateAgreement: "15/03/2024",
//       tentativeDateRecieve: "15/03/2025",
//       totalComissions: 3,
//       cpComissions: 3,
//       discountOffered: 4,
//       revenue: 15476484, 
//       comment: "great"
//     },
//     {
//       sNo: 24680,
//       invoiceNo: 13579,
//       status: "Paid",
//       buyersName: "Alice Johnson",
//       buyersContact: "Bob Williams",
//       invoiceGeneratedName: "Builders Inc",
//       invoiceGeneratedDate: "18/04//2024",
//       invoiceDate: "19/04//2024",
//       invoiceAmount: 18000,
//       GST: 14680,
//       tds: 18000,
//       amountAfterTdsDeducted: 18000,
//       finalInvoice: 18000,
//       invoiceHandedOverTo: "Shagun Khanna",
//       cancellationDate: "18/04//2024",
//       transaction: "Bob Williams",
//       representative: "Alex",
//       projectsName: "Dream Homes",
//       unitNo: "C-5432",
//       settinRepresentative: "Shagun Khanna",
//       leadSource: "Dream Homes",
//       basePrice: 18000,
//       totalPrice: 300000,
//       bookingDate: "18/12/2023",
//       tentativeDateAgreement: "18/03/2024",
//       tentativeDateRecieve: "18/03/2025",
//       totalComissions: 4,
//       cpComissions: 4,
//       discountOffered: 5,
//       revenue: 20476484, 
//       comment: "excellent"
//     },
//     {
//       sNo: 13579,
//       invoiceNo: 24680,
//       status: "Pending",
//       buyersName: "Bob Williams",
//       buyersContact: "Alice Johnson",
//       invoiceGeneratedName: "Developers Inc",
//       invoiceGeneratedDate: "21/04//2024",
//       invoiceDate: "22/04//2024",
//       invoiceAmount: 20000,
//       GST: 15890,
//       tds: 20000,
//       amountAfterTdsDeducted: 20000,
//       finalInvoice: 20000,
//       invoiceHandedOverTo: "Shagun Khanna",
//       cancellationDate: "21/04//2024",
//       transaction: "Alice Johnson",
//       representative: "Alex",
//       projectsName: "Skyline Apartments",
//       unitNo: "D-2109",
//       settinRepresentative: "Shagun Khanna",
//       leadSource: "Skyline Apartments",
//       basePrice: 20000,
//       totalPrice: 350000,
//       bookingDate: "21/12/2023",
//       tentativeDateAgreement: "21/03/2024",
//       tentativeDateRecieve: "21/03/2025",
//       totalComissions: 5,
//       cpComissions: 5,
//       discountOffered: 6,
//       revenue: 25476484, 
//       comment: "amazing"
//     },
//     {
//       sNo: 67890,
//       invoiceNo: 12345,
//       status: "Final Notice Sent",
//       buyersName: "Jane Smith",
//       buyersContact: "John Doe",
//       invoiceGeneratedName: "Developers Inc",
//       invoiceGeneratedDate: "24/04//2024",
//       invoiceDate: "25/04//2024",
//       invoiceAmount: 22000,
//       GST: 16890,
//       tds: 22000,
//       amountAfterTdsDeducted: 22000,
//       finalInvoice: 22000,
//       invoiceHandedOverTo: "Shagun Khanna",
//       cancellationDate: "24/04//2024",
//       transaction: "John Doe",
//       representative: "Alex",
//       projectsName: "Ocean View",
//       unitNo: "E-7654",
//       settinRepresentative: "Shagun Khanna",
//       leadSource: "Ocean View",
//       basePrice: 22000,
//       totalPrice: 400000,
//       bookingDate: "24/12/2023",
//       tentativeDateAgreement: "24/03/2024",
//       tentativeDateRecieve: "24/03/2025",
//       totalComissions: 6,
//       cpComissions: 6,
//       discountOffered: 7,
//       revenue: 30476484, 
//       comment: "fantastic"
//     },
//     {
//       sNo: 78901,
//       invoiceNo: 56789,
//       status: "Paid",
//       buyersName: "Tom Brown",
//       buyersContact: "Emily Davis",
//       invoiceGeneratedName: "Builders Inc",
//       invoiceGeneratedDate: "27/04//2024",
//       invoiceDate: "28/04//2024",
//       invoiceAmount: 25000,
//       GST: 17900,
//       tds: 25000,
//       amountAfterTdsDeducted: 25000,
//       finalInvoice: 25000,
//       invoiceHandedOverTo: "Shagun Khanna",
//       cancellationDate: "27/04//2024",
//       transaction: "Emily Davis",
//       representative: "Alex",
//       projectsName: "Lakeview Residency",
//       unitNo: "F-4321",
//       settinRepresentative: "Shagun Khanna",
//       leadSource: "Lakeview Residency",
//       basePrice: 25000,
//       totalPrice: 450000,
//       bookingDate: "27/12/2023",
//       tentativeDateAgreement: "27/03/2024",
//       tentativeDateRecieve: "27/03/2025",
//       totalComissions: 7,
//       cpComissions: 7,
//       discountOffered: 8,
//       revenue: 35476484, 
//       comment: "incredible"
//     },
//     {
//       sNo: 89012,
//       invoiceNo: 45678,
//       status: "Pending",
//       buyersName: "Emily Davis",
//       buyersContact: "Tom Brown",
//       invoiceGeneratedName: "Developers Inc",
//       invoiceGeneratedDate: "30/04//2024",
//       invoiceDate: "01/05//2024",
//       invoiceAmount: 28000,
//       GST: 18900,
//       tds: 28000,
//       amountAfterTdsDeducted: 28000,
//       finalInvoice: 28000,
//       invoiceHandedOverTo: "Shagun Khanna",
//       cancellationDate: "30/04//2024",
//       transaction: "Tom Brown",
//       representative: "Alex",
//       projectsName: "Hillside Villas",
//       unitNo: "G-8765",
//       settinRepresentative: "Shagun Khanna",
//       leadSource: "Hillside Villas",
//       basePrice: 28000,
//       totalPrice: 500000,
//       bookingDate: "30/12/2023",
//       tentativeDateAgreement: "30/03/2024",
//       tentativeDateRecieve: "30/03/2025",
//       totalComissions: 8,
//       cpComissions: 8,
//       discountOffered: 9,
//       revenue: 40476484, 
//       comment: "remarkable"
//     },
//     {
//       sNo: 90123,
//       invoiceNo: 34567,
//       status: "Final Notice Sent",
//       buyersName: "Emily Davis",
//       buyersContact: "Tom Brown",
//       invoiceGeneratedName: "Developers Inc",
//       invoiceGeneratedDate: "03/05//2024",
//       invoiceDate: "04/05//2024",
//       invoiceAmount: 30000,
//       GST: 19800,
//       tds: 30000,
//       amountAfterTdsDeducted: 30000,
//       finalInvoice: 30000,
//       invoiceHandedOverTo: "Shagun Khanna",
//       cancellationDate: "03/05//2024",
//       transaction: "Tom Brown",
//       representative: "Alex",
//       projectsName: "Sunset Residences",
//       unitNo: "H-5432",
//       settinRepresentative: "Shagun Khanna",
//       leadSource: "Sunset Residences",
//       basePrice: 30000,
//       totalPrice: 550000,
//       bookingDate: "03/12/2023",
//       tentativeDateAgreement: "03/03/2024",
//       tentativeDateRecieve: "03/03/2025",
//       totalComissions: 9,
//       cpComissions: 9,
//       discountOffered: 10,
//       revenue: 45476484, 
//       comment: "outstanding"
//     },
//     {
//         sNo: 90123,
//         invoiceNo: 34567,
//         status: "Final Notice Sent",
//         buyersName: "Emily Davis",
//         buyersContact: "Tom Brown",
//         invoiceGeneratedName: "Developers Inc",
//         invoiceGeneratedDate: "03/05//2024",
//         invoiceDate: "04/05//2024",
//         invoiceAmount: 30000,
//         GST: 19800,
//         tds: 30000,
//         amountAfterTdsDeducted: 30000,
//         finalInvoice: 30000,
//         invoiceHandedOverTo: "Shagun Khanna",
//         cancellationDate: "03/05//2024",
//         transaction: "Tom Brown",
//         representative: "Alex",
//         projectsName: "Sunset Residences",
//         unitNo: "H-5432",
//         settinRepresentative: "Shagun Khanna",
//         leadSource: "Sunset Residences",
//         basePrice: 30000,
//         totalPrice: 550000,
//         bookingDate: "03/12/2023",
//         tentativeDateAgreement: "03/03/2024",
//         tentativeDateRecieve: "03/03/2025",
//         totalComissions: 9,
//         cpComissions: 9,
//         discountOffered: 10,
//         revenue: 45476484, 
//         comment: "outstanding"
//     },
//     {
//         sNo: 56783,
//         invoiceNo: 59234,
//         status: "Final Notice Sent",
//         buyersName: "Kristin Watson",
//         buyersContact: "Esther Howards",
//         invoiceGeneratedName: "Developers Name",
//         invoiceGeneratedDate: "12/04//2024",
//         invoiceDate: "13/04//2024",
//         invoiceAmount: 12000,
//         GST: 12435,
//         tds: 12000,
//         amountAfterTdsDeducted: 12000,
//         finalInvoice: 12000,
//         invoiceHandedOverTo: "Shagun Khanna",
//         cancellationDate: "12/04//2024",
//         transaction: "Esther Howard",
//         representative: "jenny",
//         projectsName: "99 acres",
//         unitNo: "A-3456",
//         settinRepresentative: "Shagun Khanna",
//         leadSource: "99 acres",
//         basePrice: 12000,
//         totalPrice: 200000,
//         bookingDate: "12/12/2023",
//         tentativeDateAgreement: "12/03/2024",
//         tentativeDateRecieve: "12/03/2025",
//         totalComissions: 8,
//         cpComissions: 8,
//         discountOffered: 9,
//         revenue: 40476484, 
//         comment: "remarkable"
//     },
//     {
//         sNo: 12345,
//         invoiceNo: 67890,
//         status: "Pending",
//         buyersName: "Michael Johnson",
//         buyersContact: "Sarah Adams",
//         invoiceGeneratedName: "Builders Inc",
//         invoiceGeneratedDate: "05/06//2024",
//         invoiceDate: "06/06//2024",
//         invoiceAmount: 25000,
//         GST: 16500,
//         tds: 25000,
//         amountAfterTdsDeducted: 25000,
//         finalInvoice: 25000,
//         invoiceHandedOverTo: "Shagun Khanna",
//         cancellationDate: "05/06//2024",
//         transaction: "Sarah Adams",
//         representative: "Alex",
//         projectsName: "Green Meadows",
//         unitNo: "B-9876",
//         settinRepresentative: "Shagun Khanna",
//         leadSource: "Green Meadows",
//         basePrice: 25000,
//         totalPrice: 450000,
//         bookingDate: "05/11/2023",
//         tentativeDateAgreement: "05/04/2024",
//         tentativeDateRecieve: "05/04/2025",
//         totalComissions: 7,
//         cpComissions: 7,
//         discountOffered: 8,
//         revenue: 35476484, 
//         comment: "impressive"
//     },
//     {
//         sNo: 23456,
//         invoiceNo: 78901,
//         status: "Pending",
//         buyersName: "Olivia Wilson",
//         buyersContact: "Michael Johnson",
//         invoiceGeneratedName: "Builders Inc",
//         invoiceGeneratedDate: "07/07//2024",
//         invoiceDate: "08/07//2024",
//         invoiceAmount: 27000,
//         GST: 17820,
//         tds: 27000,
//         amountAfterTdsDeducted: 27000,
//         finalInvoice: 27000,
//         invoiceHandedOverTo: "Shagun Khanna",
//         cancellationDate: "07/07//2024",
//         transaction: "Michael Johnson",
//         representative: "Alex",
//         projectsName: "Ocean View",
//         unitNo: "C-7654",
//         settinRepresentative: "Shagun Khanna",
//         leadSource: "Ocean View",
//         basePrice: 27000,
//         totalPrice: 500000,
//         bookingDate: "07/10/2023",
//         tentativeDateAgreement: "07/05/2024",
//         tentativeDateRecieve: "07/05/2025",
//         totalComissions: 6,
//         cpComissions: 6,
//         discountOffered: 7,
//         revenue: 30476484, 
//         comment: "excellent"
//     },
//     {
//         sNo: 34567,
//         invoiceNo: 89012,
//         status: "Pending",
//         buyersName: "Sophia Brown",
//         buyersContact: "Olivia Wilson",
//         invoiceGeneratedName: "Builders Inc",
//         invoiceGeneratedDate: "09/08//2024",
//         invoiceDate: "10/08//2024",
//         invoiceAmount: 29000,
//         GST: 19140,
//         tds: 29000,
//         amountAfterTdsDeducted: 29000,
//         finalInvoice: 29000,
//         invoiceHandedOverTo: "Shagun Khanna",
//         cancellationDate: "09/08//2024",
//         transaction: "Olivia Wilson",
//         representative: "Alex",
//         projectsName: "Lakeview Apartments",
//         unitNo: "D-5432",
//         settinRepresentative: "Shagun Khanna",
//         leadSource: "Lakeview Apartments",
//         basePrice: 29000,
//         totalPrice: 550000,
//         bookingDate: "09/01/2023",
//         tentativeDateAgreement: "09/06/2024",
//         tentativeDateRecieve: "09/06/2025",
//         totalComissions: 5,
//         cpComissions: 5,
//         discountOffered: 6,
//         revenue: 25476484, 
//         comment: "wonderful"
//     },
//     {
//         sNo: 45678,
//         invoiceNo: 90123,
//         status: "Pending",
//         buyersName: "Ava Miller",
//         buyersContact: "Sophia Brown",
//         invoiceGeneratedName: "Builders Inc",
//         invoiceGeneratedDate: "11/09//2024",
//         invoiceDate: "12/09//2024",
//         invoiceAmount: 31000,
//         GST: 20460,
//         tds: 31000,
//         amountAfterTdsDeducted: 31000,
//         finalInvoice: 31000,
//         invoiceHandedOverTo: "Shagun Khanna",
//         cancellationDate: "11/09//2024",
//         transaction: "Sophia Brown",
//         representative: "Alex",
//         projectsName: "Riverfront Residency",
//         unitNo: "E-8765",
//         settinRepresentative: "Shagun Khanna",
//         leadSource: "Riverfront Residency",
//         basePrice: 31000,
//         totalPrice: 600000,
//         bookingDate: "11/02/2023",
//         tentativeDateAgreement: "11/07/2024",
//         tentativeDateRecieve: "11/07/2025",
//         totalComissions: 4,
//         cpComissions: 4,
//         discountOffered: 5,
//         revenue: 20476484, 
//         comment: "amazing"
//     },
//     {
//         sNo: 45678,
//         invoiceNo: 90123,
//         status: "Pending",
//         buyersName: "Ava Miller",
//         buyersContact: "Sophia Brown",
//         invoiceGeneratedName: "Builders Inc",
//         invoiceGeneratedDate: "11/09//2024",
//         invoiceDate: "12/09//2024",
//         invoiceAmount: 31000,
//         GST: 20460,
//         tds: 31000,
//         amountAfterTdsDeducted: 31000,
//         finalInvoice: 31000,
//         invoiceHandedOverTo: "Shagun Khanna",
//         cancellationDate: "11/09//2024",
//         transaction: "Sophia Brown",
//         representative: "Alex",
//         projectsName: "Riverfront Residency",
//         unitNo: "E-8765",
//         settinRepresentative: "Shagun Khanna",
//         leadSource: "Riverfront Residency",
//         basePrice: 31000,
//         totalPrice: 600000,
//         bookingDate: "11/02/2023",
//         tentativeDateAgreement: "11/07/2024",
//         tentativeDateRecieve: "11/07/2025",
//         totalComissions: 4,
//         cpComissions: 4,
//         discountOffered: 5,
//         revenue: 20476484, 
//         comment: "amazing"
//     },
//     {
//         sNo: 12345,
//         invoiceNo: 67890,
//         status: "Pending",
//         buyersName: "John Doe",
//         buyersContact: "Jane Smith",
//         invoiceGeneratedName: "Builders Inc",
//         invoiceGeneratedDate: "11/09//2024",
//         invoiceDate: "12/09//2024",
//         invoiceAmount: 25000,
//         GST: 20460,
//         tds: 25000,
//         amountAfterTdsDeducted: 25000,
//         finalInvoice: 25000,
//         invoiceHandedOverTo: "Shagun Khanna",
//         cancellationDate: "11/09//2024",
//         transaction: "Jane Smith",
//         representative: "Alex",
//         projectsName: "Lakeview Apartments",
//         unitNo: "D-5432",
//         settinRepresentative: "Shagun Khanna",
//         leadSource: "Lakeview Apartments",
//         basePrice: 29000,
//         totalPrice: 550000,
//         bookingDate: "09/01/2023",
//         tentativeDateAgreement: "09/06/2024",
//         tentativeDateRecieve: "09/06/2025",
//         totalComissions: 5,
//         cpComissions: 5,
//         discountOffered: 6,
//         revenue: 25476484, 
//         comment: "wonderful"
//     },
//     {
//         sNo: 67890,
//         invoiceNo: 23456,
//         status: "Pending",
//         buyersName: "Michael Johnson",
//         buyersContact: "Emily Wilson",
//         invoiceGeneratedName: "Builders Inc",
//         invoiceGeneratedDate: "11/09//2024",
//         invoiceDate: "12/09//2024",
//         invoiceAmount: 28000,
//         GST: 20460,
//         tds: 28000,
//         amountAfterTdsDeducted: 28000,
//         finalInvoice: 28000,
//         invoiceHandedOverTo: "Shagun Khanna",
//         cancellationDate: "11/09//2024",
//         transaction: "Emily Wilson",
//         representative: "Alex",
//         projectsName: "Hillside Villas",
//         unitNo: "F-9876",
//         settinRepresentative: "Shagun Khanna",
//         leadSource: "Hillside Villas",
//         basePrice: 30000,
//         totalPrice: 600000,
//         bookingDate: "10/02/2023",
//         tentativeDateAgreement: "10/07/2024",
//         tentativeDateRecieve: "10/07/2025",
//         totalComissions: 6,
//         cpComissions: 6,
//         discountOffered: 7,
//         revenue: 26476484, 
//         comment: "fantastic"
//     },
//     {
//         sNo: 34567,
//         invoiceNo: 78901,
//         status: "Pending",
//         buyersName: "Sarah Williams",
//         buyersContact: "David Brown",
//         invoiceGeneratedName: "Builders Inc",
//         invoiceGeneratedDate: "11/09//2024",
//         invoiceDate: "12/09//2024",
//         invoiceAmount: 32000,
//         GST: 20460,
//         tds: 32000,
//         amountAfterTdsDeducted: 32000,
//         finalInvoice: 32000,
//         invoiceHandedOverTo: "Shagun Khanna",
//         cancellationDate: "11/09//2024",
//         transaction: "David Brown",
//         representative: "Alex",
//         projectsName: "Sunset Residences",
//         unitNo: "H-5432",
//         settinRepresentative: "Shagun Khanna",
//         leadSource: "Sunset Residences",
//         basePrice: 30000,
//         totalPrice: 550000,
//         bookingDate: "03/12/2023",
//         tentativeDateAgreement: "03/03/2024",
//         tentativeDateRecieve: "03/03/2025",
//         totalComissions: 9,
//         cpComissions: 9,
//         discountOffered: 10,
//         revenue: 45476484, 
//         comment: "outstanding"
//     },
//     {
//         sNo: 89012,
//         invoiceNo: 34567,
//         status: "Pending",
//         buyersName: "Emily Davis",
//         buyersContact: "Tom Brown",
//         invoiceGeneratedName: "Developers Inc",
//         invoiceGeneratedDate: "03/05//2024",
//         invoiceDate: "04/05//2024",
//         invoiceAmount: 30000,
//         GST: 19800,
//         tds: 30000,
//         amountAfterTdsDeducted: 30000,
//         finalInvoice: 30000,
//         invoiceHandedOverTo: "Shagun Khanna",
//         cancellationDate: "03/05//2024",
//         transaction: "Tom Brown",
//         representative: "Alex",
//         projectsName: "Sunset Residences",
//         unitNo: "H-5432",
//         settinRepresentative: "Shagun Khanna",
//         leadSource: "Sunset Residences",
//         basePrice: 30000,
//         totalPrice: 550000,
//         bookingDate: "03/12/2023",
//         tentativeDateAgreement: "03/03/2024",
//         tentativeDateRecieve: "03/03/2025",
//         totalComissions: 9,
//         cpComissions: 9,
//         discountOffered: 10,
//         revenue: 45476484, 
//         comment: "outstanding"
//     },
//     {
//         sNo: 23456,
//         invoiceNo: 89012,
//         status: "Pending",
//         buyersName: "Emma Johnson",
//         buyersContact: "William Smith",
//         invoiceGeneratedName: "Developers Inc",
//         invoiceGeneratedDate: "03/05//2024",
//         invoiceDate: "04/05//2024",
//         invoiceAmount: 28000,
//         GST: 19800,
//         tds: 28000,
//         amountAfterTdsDeducted: 28000,
//         finalInvoice: 28000,
//         invoiceHandedOverTo: "Shagun Khanna",
//         cancellationDate: "03/05//2024",
//         transaction: "William Smith",
//         representative: "Alex",
//         projectsName: "Lakeview Apartments",
//         unitNo: "D-5432",
//         settinRepresentative: "Shagun Khanna",
//         leadSource: "Lakeview Apartments",
//         basePrice: 29000,
//         totalPrice: 550000,
//         bookingDate: "09/01/2023",
//         tentativeDateAgreement: "09/06/2024",
//         tentativeDateRecieve: "09/06/2025",
//         totalComissions: 5,
//         cpComissions: 5,
//         discountOffered: 6,
//         revenue: 25476484, 
//         comment: "wonderful"
//     },
//     {
//         sNo: 23456,
//         invoiceNo: 89012,
//         status: "Pending",
//         buyersName: "Emma Johnson",
//         buyersContact: "William Smith",
//         invoiceGeneratedName: "Developers Inc",
//         invoiceGeneratedDate: "03/05//2024",
//         invoiceDate: "04/05//2024",
//         invoiceAmount: 28000,
//         GST: 19800,
//         tds: 28000,
//         amountAfterTdsDeducted: 28000,
//         finalInvoice: 28000,
//         invoiceHandedOverTo: "Shagun Khanna",
//         cancellationDate: "03/05//2024",
//         transaction: "William Smith",
//         representative: "Alex",
//         projectsName: "Lakeview Apartments",
//         unitNo: "D-5432",
//         settinRepresentative: "Shagun Khanna",
//         leadSource: "Lakeview Apartments",
//         basePrice: 29000,
//         totalPrice: 550000,
//         bookingDate: "09/01/2023",
//         tentativeDateAgreement: "09/06/2024",
//         tentativeDateRecieve: "09/06/2025",
//         totalComissions: 5,
//         cpComissions: 5,
//         discountOffered: 6,
//         revenue: 25476484, 
//         comment: "wonderful"
//     },
//     {
//         sNo: 12345,
//         invoiceNo: 67890,
//         status: "Pending",
//         buyersName: "John Doe",
//         buyersContact: "Jane Doe",
//         invoiceGeneratedName: "Builders Inc",
//         invoiceGeneratedDate: "01/01//2024",
//         invoiceDate: "02/01//2024",
//         invoiceAmount: 25000,
//         GST: 17500,
//         tds: 25000,
//         amountAfterTdsDeducted: 25000,
//         finalInvoice: 25000,
//         invoiceHandedOverTo: "Shagun Khanna",
//         cancellationDate: "01/01//2024",
//         transaction: "Jane Doe",
//         representative: "Alex",
//         projectsName: "Hillside Villas",
//         unitNo: "A-1234",
//         settinRepresentative: "Shagun Khanna",
//         leadSource: "Hillside Villas",
//         basePrice: 27000,
//         totalPrice: 500000,
//         bookingDate: "07/04/2023",
//         tentativeDateAgreement: "07/09/2024",
//         tentativeDateRecieve: "07/09/2025",
//         totalComissions: 7,
//         cpComissions: 7,
//         discountOffered: 8,
//         revenue: 22476484, 
//         comment: "fantastic"
//     },
//     {
//         sNo: 54321,
//         invoiceNo: 98765,
//         status: "Pending",
//         buyersName: "Michael Smith",
//         buyersContact: "Emily Johnson",
//         invoiceGeneratedName: "Developers Inc",
//         invoiceGeneratedDate: "05/03//2024",
//         invoiceDate: "06/03//2024",
//         invoiceAmount: 26000,
//         GST: 18200,
//         tds: 26000,
//         amountAfterTdsDeducted: 26000,
//         finalInvoice: 26000,
//         invoiceHandedOverTo: "Shagun Khanna",
//         cancellationDate: "05/03//2024",
//         transaction: "Emily Johnson",
//         representative: "Alex",
//         projectsName: "Seaside Condos",
//         unitNo: "C-4321",
//         settinRepresentative: "Shagun Khanna",
//         leadSource: "Seaside Condos",
//         basePrice: 28000,
//         totalPrice: 520000,
//         bookingDate: "05/10/2023",
//         tentativeDateAgreement: "05/15/2024",
//         tentativeDateRecieve: "05/15/2025",
//         totalComissions: 6,
//         cpComissions: 6,
//         discountOffered: 7,
//         revenue: 23476484, 
//         comment: "amazing"
//     },
//     {
//         sNo: 67890,
//         invoiceNo: 23456,
//         status: "Pending",
//         buyersName: "Sophia Brown",
//         buyersContact: "Ava Miller",
//         invoiceGeneratedName: "Builders Inc",
//         invoiceGeneratedDate: "09/07//2024",
//         invoiceDate: "10/07//2024",
//         invoiceAmount: 30000,
//         GST: 21000,
//         tds: 30000,
//         amountAfterTdsDeducted: 30000,
//         finalInvoice: 30000,
//         invoiceHandedOverTo: "Shagun Khanna",
//         cancellationDate: "09/07//2024",
//         transaction: "Ava Miller",
//         representative: "Alex",
//         projectsName: "Riverside Homes",
//         unitNo: "B-3456",
//         settinRepresentative: "Shagun Khanna",
//         leadSource: "Riverside Homes",
//         basePrice: 32000,
//         totalPrice: 580000,
//         bookingDate: "09/12/2023",
//         tentativeDateAgreement: "09/17/2024",
//         tentativeDateRecieve: "09/17/2025",
//         totalComissions: 8,
//         cpComissions: 8,
//         discountOffered: 9,
//         revenue: 24476484, 
//         comment: "excellent"
//     },
//     {
//         sNo: 98765,
//         invoiceNo: 54321,
//         status: "Pending",
//         buyersName: "William Smith",
//         buyersContact: "Emma Johnson",
//         invoiceGeneratedName: "Developers Inc",
//         invoiceGeneratedDate: "07/05//2024",
//         invoiceDate: "08/05//2024",
//         invoiceAmount: 29000,
//         GST: 20300,
//         tds: 29000,
//         amountAfterTdsDeducted: 29000,
//         finalInvoice: 29000,
//         invoiceHandedOverTo: "Shagun Khanna",
//         cancellationDate: "07/05//2024",
//         transaction: "Emma Johnson",
//         representative: "Alex",
//         projectsName: "Hilltop Residences",
//         unitNo: "F-6543",
//         settinRepresentative: "Shagun Khanna",
//         leadSource: "Hilltop Residences",
//         basePrice: 33000,
//         totalPrice: 600000,
//         bookingDate: "07/12/2023",
//         tentativeDateAgreement: "07/17/2024",
//         tentativeDateRecieve: "07/17/2025",
//         totalComissions: 9,
//         cpComissions: 9,
//         discountOffered: 10,
//         revenue: 25476484, 
//         comment: "outstanding"
//     },
//     {
//         sNo: 98765,
//         invoiceNo: 54321,
//         status: "Pending",
//         buyersName: "William Smith",
//         buyersContact: "Emma Johnson",
//         invoiceGeneratedName: "Developers Inc",
//         invoiceGeneratedDate: "07/05//2024",
//         invoiceDate: "08/05//2024",
//         invoiceAmount: 29000,
//         GST: 20300,
//         tds: 29000,
//         amountAfterTdsDeducted: 29000,
//         finalInvoice: 29000,
//         invoiceHandedOverTo: "Shagun Khanna",
//         cancellationDate: "07/05//2024",
//         transaction: "Emma Johnson",
//         representative: "Alex",
//         projectsName: "Hilltop Residences",
//         unitNo: "F-6543",
//         settinRepresentative: "Shagun Khanna",
//         leadSource: "Hilltop Residences",
//         basePrice: 33000,
//         totalPrice: 600000,
//         bookingDate: "07/12/2023",
//         tentativeDateAgreement: "07/17/2024",
//         tentativeDateRecieve: "07/17/2025",
//         totalComissions: 9,
//         cpComissions: 9,
//         discountOffered: 10,
//         revenue: 25476484, 
//         comment: "outstanding"
//     },
//     {
//         sNo: 12345,
//         invoiceNo: 67890,
//         status: "Pending",
//         buyersName: "John Doe",
//         buyersContact: "Jane Smith",
//         invoiceGeneratedName: "Builders Inc",
//         invoiceGeneratedDate: "06/05//2024",
//         invoiceDate: "07/05//2024",
//         invoiceAmount: 28000,
//         GST: 19800,
//         tds: 28000,
//         amountAfterTdsDeducted: 28000,
//         finalInvoice: 28000,
//         invoiceHandedOverTo: "Shagun Khanna",
//         cancellationDate: "06/05//2024",
//         transaction: "Jane Smith",
//         representative: "Alex",
//         projectsName: "Lakeview Apartments",
//         unitNo: "D-5432",
//         settinRepresentative: "Shagun Khanna",
//         leadSource: "Lakeview Apartments",
//         basePrice: 29000,
//         totalPrice: 550000,
//         bookingDate: "09/01/2023",
//         tentativeDateAgreement: "09/06/2024",
//         tentativeDateRecieve: "09/06/2025",
//         totalComissions: 5,
//         cpComissions: 5,
//         discountOffered: 6,
//         revenue: 25476484, 
//         comment: "wonderful"
//     },
//     {
//         sNo: 23456,
//         invoiceNo: 89012,
//         status: "Pending",
//         buyersName: "Emma Johnson",
//         buyersContact: "William Smith",
//         invoiceGeneratedName: "Developers Inc",
//         invoiceGeneratedDate: "03/05//2024",
//         invoiceDate: "04/05//2024",
//         invoiceAmount: 28000,
//         GST: 19800,
//         tds: 28000,
//         amountAfterTdsDeducted: 28000,
//         finalInvoice: 28000,
//         invoiceHandedOverTo: "Shagun Khanna",
//         cancellationDate: "03/05//2024",
//         transaction: "William Smith",
//         representative: "Alex",
//         projectsName: "Lakeview Apartments",
//         unitNo: "D-5432",
//         settinRepresentative: "Shagun Khanna",
//         leadSource: "Lakeview Apartments",
//         basePrice: 29000,
//         totalPrice: 550000,
//         bookingDate: "09/01/2023",
//         tentativeDateAgreement: "09/06/2024",
//         tentativeDateRecieve: "09/06/2025",
//         totalComissions: 5,
//         cpComissions: 5,
//         discountOffered: 6,
//         revenue: 25476484, 
//         comment: "wonderful"
//     },
//     {
//         sNo: 34567,
//         invoiceNo: 90123,
//         status: "Pending",
//         buyersName: "Sophia Brown",
//         buyersContact: "Ava Miller",
//         invoiceGeneratedName: "Builders Inc",
//         invoiceGeneratedDate: "11/09//2024",
//         invoiceDate: "12/09//2024",
//         invoiceAmount: 31000,
//         GST: 20460,
//         tds: 31000,
//         amountAfterTdsDeducted: 31000,
//         finalInvoice: 31000,
//         invoiceHandedOverTo: "Shagun Khanna",
//         cancellationDate: "11/09//2024",
//         transaction: "Ava Miller",
//         representative: "Alex",
//         projectsName: "Riverfront Residency",
//         unitNo: "E-8765",
//         settinRepresentative: "Shagun Khanna",
//         leadSource: "Riverfront Residency",
//         basePrice: 31000,
//         totalPrice: 600000,
//         bookingDate: "11/02/2023",
//         tentativeDateAgreement: "11/07/2024",
//         tentativeDateRecieve: "11/07/2025",
//         totalComissions: 4,
//         cpComissions: 4,
//         discountOffered: 5,
//         revenue: 20476484, 
//         comment: "amazing"
//     },
//     {
//         sNo: 34567,
//         invoiceNo: 90123,
//         status: "Pending",
//         buyersName: "Sophia Brown",
//         buyersContact: "Ava Miller",
//         invoiceGeneratedName: "Builders Inc",
//         invoiceGeneratedDate: "11/09//2024",
//         invoiceDate: "12/09//2024",
//         invoiceAmount: 31000,
//         GST: 20460,
//         tds: 31000,
//         amountAfterTdsDeducted: 31000,
//         finalInvoice: 31000,
//         invoiceHandedOverTo: "Shagun Khanna",
//         cancellationDate: "11/09//2024",
//         transaction: "Ava Miller",
//         representative: "Alex",
//         projectsName: "Riverfront Residency",
//         unitNo: "E-8765",
//         settinRepresentative: "Shagun Khanna",
//         leadSource: "Riverfront Residency",
//         basePrice: 31000,
//         totalPrice: 600000,
//         bookingDate: "11/02/2023",
//         tentativeDateAgreement: "11/07/2024",
//         tentativeDateRecieve: "11/07/2025",
//         totalComissions: 4,
//         cpComissions: 4,
//         discountOffered: 5,
//         revenue: 20476484, 
//         comment: "amazing"
//     },
//     {
//         sNo: 12345,
//         invoiceNo: 67890,
//         status: "Pending",
//         buyersName: "Olivia Wilson",
//         buyersContact: "Ethan Davis",
//         invoiceGeneratedName: "Developers Inc",
//         invoiceGeneratedDate: "05/03//2024",
//         invoiceDate: "06/03//2024",
//         invoiceAmount: 27000,
//         GST: 19080,
//         tds: 27000,
//         amountAfterTdsDeducted: 27000,
//         finalInvoice: 27000,
//         invoiceHandedOverTo: "Shagun Khanna",
//         cancellationDate: "05/03//2024",
//         transaction: "Ethan Davis",
//         representative: "Alex",
//         projectsName: "Hillside Condos",
//         unitNo: "F-4321",
//         settinRepresentative: "Shagun Khanna",
//         leadSource: "Hillside Condos",
//         basePrice: 28000,
//         totalPrice: 520000,
//         bookingDate: "05/10/2023",
//         tentativeDateAgreement: "05/15/2024",
//         tentativeDateRecieve: "05/15/2025",
//         totalComissions: 6,
//         cpComissions: 6,
//         discountOffered: 7,
//         revenue: 22476484, 
//         comment: "fantastic"
//     },
//     {
//         sNo: 23456,
//         invoiceNo: 78901,
//         status: "Pending",
//         buyersName: "Liam Martinez",
//         buyersContact: "Mia Garcia",
//         invoiceGeneratedName: "Builders Inc",
//         invoiceGeneratedDate: "07/05//2024",
//         invoiceDate: "08/05//2024",
//         invoiceAmount: 29000,
//         GST: 20300,
//         tds: 29000,
//         amountAfterTdsDeducted: 29000,
//         finalInvoice: 29000,
//         invoiceHandedOverTo: "Shagun Khanna",
//         cancellationDate: "07/05//2024",
//         transaction: "Mia Garcia",
//         representative: "Alex",
//         projectsName: "Lakeview Apartments",
//         unitNo: "D-5432",
//         settinRepresentative: "Shagun Khanna",
//         leadSource: "Lakeview Apartments",
//         basePrice: 30000,
//         totalPrice: 550000,
//         bookingDate: "07/01/2023",
//         tentativeDateAgreement: "07/06/2024",
//         tentativeDateRecieve: "07/06/2025",
//         totalComissions: 5,
//         cpComissions: 5,
//         discountOffered: 6,
//         revenue: 25476484, 
//         comment: "wonderful"
//     },
//     {
//         sNo: 45678,
//         invoiceNo: 89012,
//         status: "Pending",
//         buyersName: "Noah Anderson",
//         buyersContact: "Isabella Taylor",
//         invoiceGeneratedName: "Developers Inc",
//         invoiceGeneratedDate: "09/09//2024",
//         invoiceDate: "10/09//2024",
//         invoiceAmount: 32000,
//         GST: 22400,
//         tds: 32000,
//         amountAfterTdsDeducted: 32000,
//         finalInvoice: 32000,
//         invoiceHandedOverTo: "Shagun Khanna",
//         cancellationDate: "09/09//2024",
//         transaction: "Isabella Taylor",
//         representative: "Alex",
//         projectsName: "Seaside Villas",
//         unitNo: "G-9876",
//         settinRepresentative: "Shagun Khanna",
//         leadSource: "Seaside Villas",
//         basePrice: 33000,
//         totalPrice: 650000,
//         bookingDate: "09/03/2023",
//         tentativeDateAgreement: "09/08/2024",
//         tentativeDateRecieve: "09/08/2025",
//         totalComissions: 7,
//         cpComissions: 7,
//         discountOffered: 8,
//         revenue: 26476484, 
//         comment: "incredible"
//     },
//     {
//         sNo: 45678,
//         invoiceNo: 89012,
//         status: "Pending",
//         buyersName: "Noah Anderson",
//         buyersContact: "Isabella Taylor",
//         invoiceGeneratedName: "Developers Inc",
//         invoiceGeneratedDate: "09/09//2024",
//         invoiceDate: "10/09//2024",
//         invoiceAmount: 32000,
//         GST: 22400,
//         tds: 32000,
//         amountAfterTdsDeducted: 32000,
//         finalInvoice: 32000,
//         invoiceHandedOverTo: "Shagun Khanna",
//         cancellationDate: "09/09//2024",
//         transaction: "Isabella Taylor",
//         representative: "Alex",
//         projectsName: "Seaside Villas",
//         unitNo: "G-9876",
//         settinRepresentative: "Shagun Khanna",
//         leadSource: "Seaside Villas",
//         basePrice: 33000,
//         totalPrice: 650000,
//         bookingDate: "09/03/2023",
//         tentativeDateAgreement: "09/08/2024",
//         tentativeDateRecieve: "09/08/2025",
//         totalComissions: 7,
//         cpComissions: 7,
//         discountOffered: 8,
//         revenue: 26476484, 
//         comment: "incredible"
//     },

// ]